name: CI - Dev - Docker Container Image

on:
  push:
    branches:
      - main
      - 'release-*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  set-params:
    if: github.event.repository.fork != true
    runs-on: ubuntu-latest
    outputs:
      epp_name: ${{ steps.version.outputs.epp_name }}
      sidecar_name: ${{ steps.version.outputs.sidecar_name }}
      coordinator_name: ${{ steps.version.outputs.coordinator_name }}
      epp_base_name: ${{ steps.version.outputs.epp_base_name }}
      sidecar_base_name: ${{ steps.version.outputs.sidecar_base_name }}
      coordinator_base_name: ${{ steps.version.outputs.coordinator_base_name }}
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Set image names
        id: version
        run: |
          repo="${GITHUB_REPOSITORY##*/}"
          echo "epp_name=${repo}-endpoint-picker-dev" >> "$GITHUB_OUTPUT"
          echo "sidecar_name=${repo}-disagg-sidecar-dev" >> "$GITHUB_OUTPUT"
          echo "coordinator_name=${repo}-coordinator-dev" >> "$GITHUB_OUTPUT"
          echo "epp_base_name=${repo}-endpoint-picker" >> "$GITHUB_OUTPUT"
          echo "sidecar_base_name=${repo}-disagg-sidecar" >> "$GITHUB_OUTPUT"
          echo "coordinator_base_name=${repo}-coordinator" >> "$GITHUB_OUTPUT"

      - name: Set branch name as tag
        id: tag
        run: |
          echo "tag=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"

  build-and-push:
    if: github.event.repository.fork != true
    needs: set-params
    uses: ./.github/workflows/ci-build-images.yaml
    with:
      epp-image-name: ${{ needs.set-params.outputs.epp_name }}
      sidecar-image-name: ${{ needs.set-params.outputs.sidecar_name }}
      coordinator-image-name: ${{ needs.set-params.outputs.coordinator_name }}
      tag: ${{ needs.set-params.outputs.tag }}
      prerelease: true
      chart-suffix: ""
      epp-additional-tags: ghcr.io/llm-d/${{ needs.set-params.outputs.epp_base_name }}:main
      sidecar-additional-tags: ghcr.io/llm-d/${{ needs.set-params.outputs.sidecar_base_name }}:main
      coordinator-additional-tags: ghcr.io/llm-d/${{ needs.set-params.outputs.coordinator_base_name }}:main

